const products = [
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
  {
    title: "vaskela",
    price: 12000,
    square: 190,
    floors: 2,
    bathrooms: 2,
    bedrooms: 3,
    placeSquare: 100,

    imgSrcArray: {
      webp: [
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
        "./img/catalogue/01-2-2x.webp",
        "./img/catalogue/01-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
        "./img/catalogue/01-2.jpg",
        "./img/catalogue/01-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "loftonen",
    price: 19000,
    square: 350,
    floors: 3,
    bathrooms: 3,
    bedrooms: 4,
    placeSquare: 100,
    imgSrcArray: {
      webp: [
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
        "./img/catalogue/02-2-2x.webp",
        "./img/catalogue/02-2.webp",
        "./img/catalogue/01-1-2x.webp",
        "./img/catalogue/01-1.webp",
      ],
      jpg: [
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
        "./img/catalogue/02-2.jpg",
        "./img/catalogue/02-2-2x.jpg",
        "./img/catalogue/01-1.jpg",
        "./img/catalogue/01-1-2x.jpg",
      ],
    },
  },
  {
    title: "ostamo",
    price: 17000,
    square: 400,
    floors: 3,
    bathrooms: 3,
    bedrooms: 2,
    placeSquare: 200,

    imgSrcArray: {
      webp: [
        "./img/catalogue/03-1-2x.webp",
        "./img/catalogue/03-1.webp",
        "./img/catalogue/03-2-2x.webp",
        "./img/catalogue/03-2.webp",
        "./img/catalogue/02-1-2x.webp",
        "./img/catalogue/02-1.webp",
      ],
      jpg: [
        "./img/catalogue/03-1.jpg",
        "./img/catalogue/03-1-2x.jpg",
        "./img/catalogue/03-2.jpg",
        "./img/catalogue/03-2-2x.jpg",
        "./img/catalogue/02-1.jpg",
        "./img/catalogue/02-1-2x.jpg",
      ],
    },
  },
];
export default products;
